# Generated by Django 4.2.1 on 2023-05-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('urltoimage', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
